name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        exclude: 
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: log node node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: log node node version
        run: | 
          node -v
          echo $IS_UBUNTU_8


